[user]
root = "path/to/your/root"
ratio_threshold = 56

[dev]
version = "1.1.2"
ascii = """

   ▄████▄  ▒█████ ▓█████ █    ██  ██████ 
  ▒██▀ ▀█ ▒██▒  ██▓█   ▀ ██  ▓██▒██    ▒ 
  ▒▓█    ▄▒██░  ██▒███  ▓██  ▒██░ ▓██▄   
  ▒▓▓▄ ▄██▒██   ██▒▓█  ▄▓▓█  ░██░ ▒   ██▒
  ▒ ▓███▀ ░ ████▓▒░▒████▒▒█████▓▒██████▒▒
  ░ ░▒ ▒  ░ ▒░▒░▒░░░ ▒░ ░▒▓▒ ▒ ▒▒ ▒▓▒ ▒ ░
    ░  ▒    ░ ▒ ▒░ ░ ░  ░░▒░ ░ ░░ ░▒  ░ ░
    """

[window]
columns = 45
lines = 45
